vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       musics:
           uri_prefix: /images/musics
           upload_destination: '%kernel.project_dir%/public/images/musics'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       music:
           uri_prefix: /music
           upload_destination: '%kernel.project_dir%/public/music'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        
